// Copyright 2026 GameDevBench. PoolManager editor K2 node source tests (Bomber).

#include "CoreMinimal.h"
#include "Misc/AutomationTest.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace BomberPoolManagerEditorK2Tests
{
	static bool LoadPluginSource(const TCHAR* RelativePath, FString& OutSource)
	{
		const FString SourcePath = FPaths::ConvertRelativePathToFull(FPaths::ProjectDir() / RelativePath);
		return FFileHelper::LoadFileToString(OutSource, *SourcePath);
	}
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FBomberPoolManagerK2_BaseNodePinAndTypeSource,
	"Bomber.PoolManagerEditorK2.base_node_pin_and_type_source",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)

bool FBomberPoolManagerK2_BaseNodePinAndTypeSource::RunTest(const FString& Parameters)
{
	// REQUIRED: validates the editor-facing pin allocation, type propagation, reconstruction, menu, and graph compatibility paths.
	FString Source;
	if (!TestTrue(TEXT("K2Node_TakeFromPoolBase.cpp must be readable"),
		BomberPoolManagerEditorK2Tests::LoadPluginSource(TEXT("Plugins/PoolManager/Source/PoolManagerEditor/Private/K2Node_TakeFromPoolBase.cpp"), Source)))
	{
		return true;
	}

	TestTrue(TEXT("Base node must allocate an input exec pin"), Source.Contains(TEXT("PN_Execute")));
	TestTrue(TEXT("Base node must allocate Completed and Failed exec outputs"),
		Source.Contains(TEXT("PN_Completed")) && Source.Contains(TEXT("GetFailedPinName()")));
	TestTrue(TEXT("Base node must allocate the PoolManager target pin"),
		Source.Contains(TEXT("UPoolManagerSubsystem::StaticClass()")) && Source.Contains(TEXT("PN_Self")));
	TestTrue(TEXT("Base node must allocate an ObjectClass class pin"),
		Source.Contains(TEXT("PC_Class")) && Source.Contains(TEXT("GetClassInputPinName()")));
	TestTrue(TEXT("Base node must allocate a priority enum input"),
		Source.Contains(TEXT("ESpawnRequestPriority")) && Source.Contains(TEXT("GetPriorityPinName()")));
	TestTrue(TEXT("Base node must update output pin type from selected class"),
		Source.Contains(TEXT("OnClassPinChanged")) && Source.Contains(TEXT("PinSubCategoryObject")) && Source.Contains(TEXT("GetAuthoritativeClass()")));
	TestTrue(TEXT("Class pin changes must reconnect compatible output links"),
		Source.Contains(TEXT("BreakAllPinLinks")) && Source.Contains(TEXT("TryCreateConnection")));
	TestTrue(TEXT("Reconstruction must preserve selected output type"),
		Source.Contains(TEXT("ReallocatePinsDuringReconstruction")) && Source.Contains(TEXT("GetSelectedClass(&OldPins)")));
	TestTrue(TEXT("Reconstruction must migrate legacy Then pin to Completed"),
		Source.Contains(TEXT("OldThenPin")) && Source.Contains(TEXT("PN_Then")) && Source.Contains(TEXT("PN_Completed")));
	TestTrue(TEXT("Node must register Blueprint menu actions"),
		Source.Contains(TEXT("UBlueprintNodeSpawner::Create")) && Source.Contains(TEXT("AddBlueprintAction")));
	TestTrue(TEXT("Node must be limited to ubergraphs and macros"),
		Source.Contains(TEXT("GT_Ubergraph")) && Source.Contains(TEXT("GT_Macro")));
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FBomberPoolManagerK2_BaseNodeExpansionSource,
	"Bomber.PoolManagerEditorK2.base_node_expansion_source",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)

bool FBomberPoolManagerK2_BaseNodeExpansionSource::RunTest(const FString& Parameters)
{
	// REQUIRED: validates the core compiler expansion graph generated by the base node.
	FString Source;
	if (!TestTrue(TEXT("K2Node_TakeFromPoolBase.cpp must be readable"),
		BomberPoolManagerEditorK2Tests::LoadPluginSource(TEXT("Plugins/PoolManager/Source/PoolManagerEditor/Private/K2Node_TakeFromPoolBase.cpp"), Source)))
	{
		return true;
	}

	TestTrue(TEXT("Expansion must create a sequence node"),
		Source.Contains(TEXT("UK2Node_ExecutionSequence")));
	TestTrue(TEXT("Expansion must call the native PoolManager function chosen by the derived node"),
		Source.Contains(TEXT("FunctionReference.SetExternalMember(GetNativeFunctionName()")) && Source.Contains(TEXT("UPoolManagerSubsystem::StaticClass()")));
	TestTrue(TEXT("Expansion must create a temporary output variable"),
		Source.Contains(TEXT("UK2Node_TemporaryVariable")) && Source.Contains(TEXT("SpawnInternalVariable")));
	TestTrue(TEXT("Expansion must create an assignment node for callback output"),
		Source.Contains(TEXT("UK2Node_AssignmentStatement")));
	TestTrue(TEXT("Expansion must create a completed delegate custom event"),
		Source.Contains(TEXT("UK2Node_CustomEvent")) && Source.Contains(TEXT("DelegateOutputName")));
	TestTrue(TEXT("Expansion must convert delegate signature params into output pins"),
		Source.Contains(TEXT("FDelegateProperty")) && Source.Contains(TEXT("ConvertPropertyToPinType")));
	TestTrue(TEXT("Expansion must branch Completed versus Failed on result validity"),
		Source.Contains(TEXT("UK2Node_IfThenElse")) && Source.Contains(TEXT("SpawnIsResultValidPin")));
	TestTrue(TEXT("Expansion must move user target/class/output/exec links to intermediate nodes"),
		Source.Contains(TEXT("MovePinLinksToIntermediate")) && Source.Contains(TEXT("TryCreateConnection")));
	TestTrue(TEXT("Expansion must report an internal compiler error when wiring fails"),
		Source.Contains(TEXT("MessageLog.Error")) && Source.Contains(TEXT("Internal connection error")));
	TestTrue(TEXT("Expansion must break original node links after generating the intermediate graph"),
		Source.Contains(TEXT("BreakAllNodeLinks()")));
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FBomberPoolManagerK2_SingleAndArrayNodeSource,
	"Bomber.PoolManagerEditorK2.single_and_array_node_source",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)

bool FBomberPoolManagerK2_SingleAndArrayNodeSource::RunTest(const FString& Parameters)
{
	// REQUIRED: validates the derived single-object and array node specializations.
	FString SingleSource;
	FString ArraySource;
	const bool bLoadedSingle = BomberPoolManagerEditorK2Tests::LoadPluginSource(
		TEXT("Plugins/PoolManager/Source/PoolManagerEditor/Private/K2Node_TakeFromPool.cpp"), SingleSource);
	const bool bLoadedArray = BomberPoolManagerEditorK2Tests::LoadPluginSource(
		TEXT("Plugins/PoolManager/Source/PoolManagerEditor/Private/K2Node_TakeFromPoolArray.cpp"), ArraySource);

	if (!TestTrue(TEXT("K2Node_TakeFromPool.cpp must be readable"), bLoadedSingle)
		|| !TestTrue(TEXT("K2Node_TakeFromPoolArray.cpp must be readable"), bLoadedArray))
	{
		return true;
	}

	TestTrue(TEXT("Single-object node must expand to BPTakeFromPool"),
		SingleSource.Contains(TEXT("BPTakeFromPool")));
	TestTrue(TEXT("Single-object node must allocate and forward the transform input"),
		SingleSource.Contains(TEXT("TransformInputName")) && SingleSource.Contains(TEXT("CallTransformPin")));
	TestTrue(TEXT("Array node must return an array output pin"),
		ArraySource.Contains(TEXT("ContainerType = EPinContainerType::Array")));
	TestTrue(TEXT("Array node must expand to BPTakeFromPoolArray"),
		ArraySource.Contains(TEXT("BPTakeFromPoolArray")));
	TestTrue(TEXT("Array node must allocate and forward the amount input"),
		ArraySource.Contains(TEXT("AmountInputName")) && ArraySource.Contains(TEXT("CallAmountPin")));
	TestTrue(TEXT("Array node must validate non-empty returned arrays with Array_IsValidIndex"),
		ArraySource.Contains(TEXT("Array_IsValidIndex")) && ArraySource.Contains(TEXT("IndexToTest defaults to 0")));
	return true;
}
